### ISSUE TITLE
GPS Pill

### ISSUE THREAD

**Issue by ErikSin** [digidem/comapeo-mobile#111]
GPS pill on the top of the map screen gives the user details about accuracy of their gps, and then allows the user to click on it to get more information about their location

### To Do
- [ ] Create GPS pill that sits on the top of the map screen
- [ ] Clicking on GPS pill navigates to the Coordinate information screen

### Screen shots

![Image](https://github.com/digidem/CoMapeo-mobile/assets/67773827/3687dcd7-154d-454a-8c52-f001fde41f9d)

![Image](https://github.com/digidem/CoMapeo-mobile/assets/67773827/e1f4c598-01c3-4026-b132-ddf9c180d336)

**Comment by achou11** [comment]
Already implemented. Closing in favor of (future) issues that are more specific around changes/improvements
