### ISSUE TITLE
Server Status getting stuck on `STARTING`

### ISSUE THREAD

**Issue by ErikSin** [digidem/CoMapeo-mobile#113]
On metro refresh (eg, developer presses `r` in the terminal running metro, or an edit is made in react code) the screen goes blank. This is because [ServerStatus](https://github.com/digidem/CoMapeo-mobile/blob/503a1cdb1b976671394765a4579397c8c34602a8/src/frontend/ServerLoading.tsx#L12) is being set to null. this was determined by doing a `console.log(ServerStatus)`

The current workaround, is to go to the ServerLoading file, make a change (the change doesn't actually need to effect the code. Aka, I just add a space), and save the file. This causes the metro server to refresh again, solving the issue

![Image](https://github.com/digidem/CoMapeo-mobile/assets/67773827/97d0fa89-4c49-4172-a0ee-78a5ab48bfd6)

**Comment by achou11** [comment]
just jotting some stuff down as I investigate. Noticing this in my adb logs when you trigger the initial refresh:

```
W unknown:ReactNative: Calling JS function after bridge has been destroyed: RCTNativeAppEventEmitter.emit(["nodejs-mobile-react-native-message",{"message":"{\"event\":\"server:status\",\"payload\":\"[{\\\"value\\\":\\\"STARTED\\\"}]\"}","channelName":"_EVENTS_"}])
```

My guess is that the following sequence is happening:

1. Start the app, all is good
2. Do fast refresh
3. server loading sends a status request to the backend i.e. `nodejs.channel.post('get-server-status')`
4. ServerStatus instance attempts to respond by sending a `server:status` message back to frontend
5. error above shows up

Not entirely sure if our app code is responsible for the issue or not. seems like maybe this is something that needs to be handled at the native level via nodejs-mobile-react-native (something about caching `RCTNativeAppEventEmitter` properly to properly survive fast refreshes...)

**Comment by achou11** [comment]
a naïve solution is to set up something like a heartbeat (similar to what mapeo mobile does). not ideal so would prefer to look into this more carefully. @gmaclennan if you have any thoughts, very much welcomed
