### ISSUE TITLE
memory leak in useLocation

### ISSUE THREAD

**Issue by gmaclennan** [digidem/CoMapeo-mobile#126]
useLocation creates a `setInterval`. This is not cleared when the component unmounts. Because we have an `ignore=false` check before doing a state update, nothing will happen for each interval, but it will keep running, and new intervals will be created each time the user navigates to and from a screen using this hook. This means that the function instances created can't be garbage collected, so memory usage will slowly increase.

I suggest separating concerns and making a separate hook `useLocationProviderStatus()` and handling that there. This also avoids the problem of the user not moving, which would cause the current implementation to do unnecessary `getProviderStatus()` checks (because we pass the `distanceInterval` option to `watchPositionAsync()`).

Would also use `setTimeout` for this kind of logic. Not sure why useInterval is being used.

**Comment by ErikSin** [comment]
I [created this PR](https://github.com/digidem/CoMapeo-mobile/pull/128). I don't know if this is what you had in mind. The problem with this is that we are calling the `watchPositionAsync` subscription twice every time we use the useLocationHook()
