### ISSUE TITLE
Fix Slow Start Up Time

### ISSUE THREAD

**Issue by ErikSin** [digidem/CoMapeo-mobile#171]
With slower phones, the splash screen is taking over 10 seconds to be hidden. 

Splash Screen is being hidden in the [AppNavigator](https://github.com/digidem/CoMapeo-mobile/blob/9b59f2e3a4dcc1cf4c16838cb9da2968f044c7e3/src/frontend/Navigation/AppNavigator.tsx#L42). 

## To do
- [ ] Determine what step, before app navigator, that is causing the delay.

**Comment by achou11** [comment]
experimenting a little with this and I have some suspicions that a lot of the boot time has something to do with Expo initialization (on the native side). lots of the hanging time is before the react part of the app is even started it seems
