### ISSUE TITLE
Invite flow proposal

### ISSUE THREAD

**Issue by gmaclennan** [digidem/comapeo-mobile#185]
Just had a conversation with @EvanHahn about responsibilities between backend and frontend for responding to invites. Our conclusions:

- We should keep the "already" response for the user experience of the inviter. User story: user A invites user X to a project, and around the same time, user B also invites user X to the project. user X accepts the invite from A. If we only send "reject" then user B would think user X is not part of the project, and would need to find the user and figure out what had happened. "already" allows inviters to know that their intent has succeeded "invitee is part of the project", but it was not via their invite.
- The front-end is not responsible for sending "already" responses, only "accept" or "reject".
- When an invite is received, the backend will evaluate if the device is already part of the project, and if so it will automatically send an "already" response and not expose the invite to the user.
- When an invite is accepted, the backend will send "already" responses to all other pending invites to the same project. The backend should do a second check of pending invites to response "already" once the project is joined as a result of accepting an invite.
- When an invite is rejected, the backend will take no action on pending invites to the same project.
- Duplicate invites to the same project are exposed to the front-end. The front-end chooses which to display. After accept, the front-end can assume that other pending invites to the same project will be removed by the backend before project joining is complete. After reject, the frontend can choose to either display the next pending invite to the same project, or choose to reject all pending invites to the same project.

I hope that's clear and reflects what we discussed. @ErikSin

**Comment by achou11** [comment]
Closing, as this is outdated and invite flow is mostly implemented at this point
