### ISSUE TITLE
Update observation leave warning to modal

### ISSUE THREAD

**Issue by ErikSin** [digidem/comapeo-mobile#308]
Currently when a user tries to exit creating an observation, a native toast appears asking the user if they want to discard their observation.

We want to replace this native toast with a modal.

To do
- [ ] delete native alert 
- [ ] replace with modal

![Image](https://github.com/digidem/comapeo-mobile/assets/67773827/bc508d7f-d4b2-4487-9f00-061f9b2384c6)

https://www.figma.com/file/1Knqv1NrijUuqMo1pvYyF7/Tracks-and-Audio-(Share)?type=design&node-id=0-1&mode=design&t=jd1g5GHWdEOBwkT6-0

**Comment by achou11** [comment]
Closing since already implemented
