### ISSUE TITLE
Create minimal mocked Mapeo API and build hooks for client integration

### ISSUE THREAD

**Issue by gmaclennan** [digidem/CoMapeo-mobile#5]
Create methods for `mapeo.observation.getByDocId()` and `mapeo.observation.getMany()` that return mocked data. See proposed [Datatype API docs](https://github.com/digidem/mapeo-core-docs/blob/bdaad344a4f00df654dd083ee541d29e54e63290/client-docs/datatype.md#getbydocid). I think most of the work is already done in https://github.com/digidem/mapeo-core-client-experiments (private repo)

The reason for doing this is to enable integration work to be advanced without completing work on Mapeo Core Next. As long as the shape of the API matches (or is close to) what will eventually be the Mapeo Core API, then we can just swap in the "real" Mapeo core when it is ready. We can move ahead with building out the backend process, the RPC bridge, the client API, react-query hooks, and linking the data into the screens, none of which actually needs the "real" mapeo core to be ready to complete.

We can do most of the hard integration work with this mocked Mapeo. Initially just the two APIs of `getByDocId()` and `getMany()` allow us to work on most of the screens that need this data.

- [x] manage startup of the nodejs-mobile process https://github.com/digidem/react-native-with-mapeo-core-next/issues/4
- [x] expose the api on the client via rpc-reflector https://github.com/digidem/react-native-with-mapeo-core-next/pull/3
- [x] create hooks e.g. `useObservations()` and `useObservation()` (might want to create a general abstraction using react-query, I think @achou11 or @ErikSin already did some work on this).
- [x] copy across the code for observation list view and observation view to this repo, and connect to the hooks

**Comment by ErikSin** [comment]
Completed, but won't be merged in as the real API will be completed soon
