### ISSUE TITLE
Observation Category onPress should not open Preset Chooser

### ISSUE THREAD

**Issue by ErikSin** [digidem/comapeo-mobile#512]
On the observation edit/ create screen, clicking the entire category should not open the preset chooser screen, onley pressing the change button should.

## To Do
- [ ] Remove Touchable Opacity from Category
- [ ] Add onPress function to change button

### Notion Issue
https://www.notion.so/digidem/f551401ee13f4652b3b3f23e52db9783?v=c58a7b022e084c2bae2c4379bf0c67e7&p=4c29b5d40bf74fbe9cc276fdd0f4387b&pm=s

**Comment by achou11** [comment]
Closing given that the existing behavior is preferred
