### ISSUE TITLE
Media not syncing

### ISSUE THREAD

**Issue by ErikSin** [digidem/comapeo-mobile#514]
Photos on a device seem to be not syncing properly.

## To do
- [ ] Determine and fix the issue with photos not syncing properly

## Notion Issue:
https://www.notion.so/digidem/f551401ee13f4652b3b3f23e52db9783?v=c58a7b022e084c2bae2c4379bf0c67e7&p=a4052c12ac1f4c34a97a2716d75c02d0&pm=s

**Comment by EvanHahn** [comment]
Closed in https://github.com/digidem/mapeo-core-next/pull/722.
