### ISSUE TITLE
Import Config not working

### ISSUE THREAD

**Issue by ErikSin** [digidem/comapeo-mobile#518]
Importing config is not working

## To Do
- [x] Determine why importing config is not working
- [x] Fix config import

### Notion Issue
https://www.notion.so/digidem/f551401ee13f4652b3b3f23e52db9783?v=c58a7b022e084c2bae2c4379bf0c67e7&p=4e09eecabb5047f7bac289ddd9b901a0&pm=s

**Comment by achou11** [comment]
Closed accidentally
