### ISSUE TITLE
Proposal: config name and config version from import

### ISSUE THREAD

**Issue by gmaclennan** [digidem/comapeo-mobile#527]
**MVP Candidate**

This is a proposal to include this feature in MVP, pending feedback on feasibility and timeline.

**Is your feature request related to a problem? Please describe.**

Users need a way to check whether their project is configured with a config (presets & fields), and to check whether they are using the most recent version of that config. Without that information, users have no way of knowing if a config import was successful.

This is also a problem for users using the "default" config. We may update the default config that ships with CoMapeo. Users may have a project with the default config from a previous version of Mapeo, and may desire to manually update it. They need to know the version of the default config they are using to check this.

**Describe the solution you'd like**

I would like users to be able to view a name and version for the config that their project is configured with. Tasks needed:

- [ ] Add name and version metadata to config files
- [ ] Update config builder scripts to ensure that configs have a name and version
- [ ] Decide how to handle config files that do not have a name and version. Throw an error?
- [ ] Decide how to handle attempts to import an older version of a config
- [ ] https://github.com/digidem/mapeo-schema/pull/197
- [ ] https://github.com/digidem/mapeo-core-next/pull/721
- [x] #530

I suggest we use semver for versioning configs:

- Patch changes: corrections for clarity and fixing typos to any labels, e.g. field questions or options or placeholders.
- Minor changes:
  - Changes to labels that change the meaning of a question or option
  - Addition of fields to a preset
  - Addition of new presets
  - Addition of options to a select or multi-select
- Major changes:
  - Changing tags on a preset
  - Changing key for a field
  - Removing a preset
  - Removing a field from a preset

**Comment by achou11** [comment]
just as a reminder for myself, i did a good portion of work for this screen in https://github.com/digidem/comapeo-mobile/pull/371 (of course without the important bits about version + name)

**Comment by tomasciccola** [comment]
I'm wondering about config versioning. It happens that people that build configurations don't necessarily are developers, so maintaining that versioning standard may be hard to enforce.

**Comment by tomasciccola** [comment]
Also, configs already have a `name` and `version` fields on the `metadata.json` file, that its still part of the build. So the first two items _I think_ can be marked as done

**Comment by tomasciccola** [comment]
Wondering, are this fields always mandatory? Could there be a `ProjectSettings` without this config metadata undefined?

**Comment by tomasciccola** [comment]
> We can make them mandatory - this is a new config file format that hasn't been released yet, so we can write it into the spec.

What I wonder about this is the difference between making this fields mandatory in the config vs in `projectSettings`. 
Enforcing this in the config is easy - I think - (and kind of already done). But, could there be cases where we want to `setProjectSettings` before importing a config? I think this can happen and would mean having an invalid `projectSettings` doc.

**Comment by tomasciccola** [comment]
closing as done, was actually tracked on -> https://github.com/digidem/mapeo-core-next/issues/727
