### ISSUE TITLE
Menu Update

### ISSUE THREAD

**Issue by ximenabb** [digidem/comapeo-mobile#543]
## Description
With metrics, we are now introducing a Data Privacy screen at onboarding. User can also access that Data Privacy screen via the right Menu

What we are tracking : https://www.notion.so/digidem/Metrics-MVP-70d4d2990de8407fbe599218ad5cf155

## Menu Update
<img width="180" alt="Screen Shot 2024-07-25 at 10 37 35 AM" src="https://github.com/user-attachments/assets/b3aaf85c-80d4-4090-8758-e4700108ebb9"> 

- [x]  Update screen as designed, by added a _Data & Privacy_ button under _App Settings_ (see #565)
- [x] When clicked direct to the Data Privacy screen

## Screen 2 - Data Privacy
<img width="171" alt="Screen Shot 2024-07-25 at 10 37 47 AM" src="https://github.com/user-attachments/assets/c8eb734e-bb09-4a47-9507-e5547a0f6934">

- [x] Display screen as designed
- [x] Display **CoMapeo Respects Your Privacy & Autonomy**
- [x] Display _Learn More_ button, when clicked direct to Privacy Policy screen
- [x] Display check box next to S**hare Diagnostic Information** , when clicked collect data

## Screen 3
<img width="169" alt="Screen Shot 2024-07-25 at 10 38 00 AM" src="https://github.com/user-attachments/assets/ac84b452-e4d4-4bce-8b4c-c9f1ca63ff65">

- [x] Display screen as designed
- [x]  When clicked back arrow directs to the Data Privacy screen

## Design
https://www.figma.com/design/1Knqv1NrijUuqMo1pvYyF7/%22Ready-for-Dev%22-Hand-off-Assets?node-id=934-273&t=eiLnXjdi133AXR2g-0

**Comment by EvanHahn** [comment]
This checkbox will likely set a stored boolean flag, like others in `src/frontend/hooks/persistedState/`.

Once we've done that, we'll need to update `App.tsx`. Specifically, this code:

https://github.com/digidem/comapeo-mobile/blob/dbe3536f73af85e1b245876f6749db6cdf44b3c9/src/frontend/App.tsx#L74-L77

The code above is for device diagnostic metrics. We'll also need to do that for app diagnostic metrics, which are not yet merged (see #480). The change should be very similar.
