### ISSUE TITLE
Sync / Device being Synced with doest see the progress

### ISSUE THREAD

**Issue by ximenabb** [digidem/comapeo-mobile#550]
**Describe the bug**
- Device A clicks on Sync and is syncing with Device B. 
- Device A sees the syncing progress. 
- Does Device B doesnt see any changes and the sync screen remains the same saying “1 device waiting to sync with you”

**User goal**
Device B (and any other connected device syncing) should see the same syncing state. The progress bars would progress depending on how much data they are getting/sending.

Details : https://www.notion.so/digidem/Sync-Device-being-sync-to-doesnt-see-progress-bar-bbe2a09b10804b98b34ef8f170ad6f24

**Comment by achou11** [comment]
This seems like expected behavior based on the design here, unless this is outdated:

https://www.figma.com/design/uzynHXR0xgJu19lsCoJyXN/%F0%9F%90%9A-Shell-App?node-id=1068-4024&t=C2stSJj2AxvpGgLt-0

**Comment by achou11** [comment]
> Device B (and any other connected device syncing) should see the same syncing state.

My understanding is that this shouldn't be the case, unless Device B (or any other device) have _explicitly_ opted into syncing at some prior point i.e. pressed that button on the sync screen

There's a lingering issue where we don't persist the sync opt-in after leaving that screen, so you have to press that button again in the case of leaving screen and coming back to it. but i think that's outside the scope of the issue described here

**Comment by gmaclennan** [comment]
> Device A sees the syncing progress.

@ximenabb can you describe what progress Device A sees? Does the progress on device A advance and/or complete? Or does it show a % completion and stay at that point?

**Comment by achou11** [comment]
> @ximenabb can you describe what progress Device A sees? Does the progress on device A advance and/or complete? Or does it show a % completion and stay at that point?

@gmaclennan this is my best understanding of what's being described, if helpful. (note that the syncing in the end is too fast so the progress isn't really elegantly displayed, but it worked).

https://github.com/user-attachments/assets/97a0d978-f9e8-4ab4-91a5-4a36508426b3

**Comment by gmaclennan** [comment]
Thanks, that is very helpful. It seems like the text on the device that starts to sync first is incorrect: it says "syncing with 1 device" before that device has started sync. It's not syncing with that device until that device also starts to sync. Do we have the necessary data from the core API to show this?

**Comment by achou11** [comment]
> Thanks, that is very helpful. It seems like the text on the device that starts to sync first is incorrect: it says "syncing with 1 device" before that device has started sync. It's not syncing with that device until that device also starts to sync. Do we have the necessary data from the core API to show this?

I don't think so? seems like it would require exposing another field in the sync state that relates to the number of connected peers that are opted into syncing

**Comment by achou11** [comment]
The alternative approach is to update the UI such that it's only communicating that you've enabled syncing, instead of specifics in relation to other peers.

For example, in that "idle" state (or when sync progress = 0?) the copy could say something like "Waiting to sync" and the progress bar can (optionally) be in some indeterminate state. once actual data is being synced, switch the copy to something similar to what's currently being shown

**Comment by gmaclennan** [comment]
I think it's an important feature to add to mapeo core at some stage. I've created an issue for this: https://github.com/digidem/mapeo-core-next/issues/738.

I am not sure how much of a priority this is to address for MVP?

> in that "idle" state (or when sync progress = 0?) the copy could say something like "Waiting to sync" and the progress bar can (optionally) be in some indeterminate state. once actual data is being synced, switch the copy to something similar to what's currently being shown

I think that might work as an interim solution that is easier to implement.

I realize that the designs do not include states for when a device has started syncing, but other connected devices have not started syncing. The designs only include the state for the opposite: when other connected devices have started syncing, but the current device is not syncing.

I think it is valuable for users to see why sync is not progressing, e.g. "0 / 6 devices syncing". This could all benefit from some design and copy refinements down the road.

**Comment by achou11** [comment]
This will be fixed when #602, #603, #604, and #605 are addressed
