### ISSUE TITLE
Sync / Sync and Stop buttons need to double tap to work

### ISSUE THREAD

**Issue by ximenabb** [digidem/comapeo-mobile#551]
**Describe the bug**
Problem: When i click on a button via the sync screen, i need to tap twice for it to work
Maybe a behavior across the app?

See video https://www.notion.so/digidem/Sync-Sync-and-Stop-buttons-need-to-double-tap-to-work-cc8087a80b5041bebba089f58437f032

**Comment by achou11** [comment]
Fixed via https://github.com/digidem/comapeo-mobile/pull/544 (exact fix via https://github.com/digidem/mapeo-core-next/pull/725)
