### ISSUE TITLE
Project Invite/ Device creating an observation - receives the invite - cant click

### ISSUE THREAD

**Issue by ximenabb** [digidem/comapeo-mobile#552]
**Describe the bug**

-  Device 1, not on a project, while creating an observation, still got the invite on the project
- tried to click on Accept Device but nothing happens
- Decline button doesnt work
- The inviting device cancels the invite - the invite is still there
 -  app stuck on device 1

See details : https://www.notion.so/digidem/f551401ee13f4652b3b3f23e52db9783?v=c58a7b022e084c2bae2c4379bf0c67e7&p=97c35011ddfb4a0da554df954e188b6e&pm=s

**Comment by achou11** [comment]
my understanding is that the invite shouldn't show up while you're in the create observation flow to begin with, so that seems like the first major issue here.

**Comment by ximenabb** [comment]
@achou11 correct! want me to create 2 tickets?

**Comment by achou11** [comment]
have you run into the other issues while _not_ in observation creation flow? if so, yes I'd create separate issues but if not, my guess is that fixing that first issue would be enough

**Comment by ximenabb** [comment]
nope, the issue only happened when in that state.
