### ISSUE TITLE
Project Invite/ inviting a device already on a project - still accepts invite

### ISSUE THREAD

**Issue by ximenabb** [digidem/comapeo-mobile#553]
**Describe the bug**
When a Coordinator/participant device already is on their own project/ or other poject,  if they receive an invite to another project, they can accept the invite and switch projects  - no warning to Leave Project appears

If user is already on a project, the screen should be invited to Leave Current Project or Go Back

See details : https://www.notion.so/digidem/Project-Invite-inviting-a-device-already-on-a-project-still-accepts-invite-33bd70fa08824bd086aabacdf32ab04e

Designs : https://www.figma.com/design/uzynHXR0xgJu19lsCoJyXN/%F0%9F%90%9A-Shell-App?node-id=1196-1914&t=f3oSdMmBPhOQn0zE-0
<img width="163" alt="Screen Shot 2024-07-26 at 1 41 53 PM" src="https://github.com/user-attachments/assets/964290c8-6185-4b63-abc8-227acfb63a72">

**Comment by achou11** [comment]
Should be fixed via https://github.com/digidem/comapeo-mobile/pull/526
