### ISSUE TITLE
Proposal/Idea: Create mock data for testing

### ISSUE THREAD

**Issue by gmaclennan** [digidem/comapeo-mobile#579]
**Is your feature request related to a problem? Please describe.**

As I understand it, a time-consuming aspect of QA testing CoMapeo is collecting data. Actually testing data collection is important, but as I understand it, collecting data is a pre-requisite for other tests such as sync, editing and viewing data on the map.

Because installing test versions of CoMapeo often involves deleting existing data, this can be time-consuming for a tester. They need to collect lots of data before being able to test sync.

**Describe the solution you'd like**

I would like a new menu item under "Project Settings" that only appears for test builds of the app. The menu item should contain a button "generate mock observations", possibly with an input box to enter a number of observations to create (maybe default to 20?).

This menu item should internally call `project.observation.create()`. Ideally:

- Location is randomized within a 10-50km radius/bbox of the users current location
- Categories are randomized
- Device name is added to the "notes" field to aid debugging
- Observations have a random (0 to 3) number of photos attached. Suggest: download ~10 random images from unsplash.com or similar service and then attach these (we might hit rate limits, so maybe we host some random images ourselves).

**Describe alternatives you've considered**

QA testers can keep collecting data as part of testing.

**Comment by achou11** [comment]
Refer to https://github.com/digidem/mapeo-core-next/blob/241f2a763a3b5abc8e5044a24ce8631d9183182c/test-e2e/utils.js#L489 for potential implementation

**Comment by achou11** [comment]
Will extract the parts from this issue that haven't been addressed via #592 (which is more like an initial implementation)
