### ISSUE TITLE
Custom Config imported / App Crash

### ISSUE THREAD

**Issue by ximenabb** [digidem/comapeo-mobile#686]
Have not manage to reproduce by Jen. Ximena reproduced on 2 different devices but can no longer reproduce

Details and videos - https://www.notion.so/digidem/Custom-Config-imported-App-Crash-148f4de78c1040e1aaf00f868313e749

**Comment by achou11** [comment]
Was able to reproduce this. more specifically when navigating to the observation list after loading the config. Steps to reproduce:

1. Do NOT create a project. 
2. Add some observations (I used the test data generator)
3. Import a config. Don't think it matters which one, as long as it's notably different from the default one.
4. Navigate to the observations list screen.

Got the following error after 4:

<img src="https://github.com/user-attachments/assets/2fe80a1c-cfad-4cc5-9828-2fdb3ac30f4e" width="200" />
