### ISSUE TITLE
Conversation about upgrades in general

### ISSUE THREAD

**Issue by ErikSin** [digidem/comapeo-mobile#864]

**Comment by ErikSin** [comment]
Notes here: https://www.notion.so/digidem/Conversation-About-Upgrades-14a1b08162d5808f8de1fce53d3c24f8

## Next Steps
- Review the direct dependencies monthly as well as implode package lock
    - npm outdated: lists current and outdated
    - npm check: more
- update package.json to use exact versions for both direct + dev deps (not related to Expo)
- to look into: is there a npm config variable to always save exact versions?
- add CI check to make sure that all dependencies are exact versions
- look into using https://github.com/webpro-nl/knip for specific cases initially (e.g. unused files + deps)
- integrate https://socket.dev/
- Shrinkwrapping CoMapeo core - Makes it so if you install Comapeocore uses the same version as the tests.

**Comment by achou11** [comment]
Week of Dec 2: Erik to spend 1 hour-ish to prioritize and finish within the next day. Finish = direct deps upgrades + pinning + package-lock blowup

**Comment by achou11** [comment]
What's left to do:

- upgrading dev deps: 1 day
- upgrading to Expo + friends: 1 day
- upgrading React Navigation and fix anything that's broken. estimate: 1 day
- potentially integrate Socket.dev into repo
- apply same decisions and actions to desktop
