### ISSUE TITLE
Don't enable debug logging by default in the backend

### ISSUE THREAD

**Issue by gmaclennan** [digidem/CoMapeo-mobile#99]
The new logging for mapeo-core makes the code run _really_ slowly, because it logs every state event during sync. We should not enable this by default, and also should probably reduce the amount of logging so that the slowdown is not quite so huge.

Task: Remove this line: https://github.com/digidem/CoMapeo-mobile/blob/e4b88cdafbb430a3c6a448c8ce0e57558904ac77/src/backend/src/app.js#L46

**Comment by achou11** [comment]
Addressing in #96
